max_width = 120
tab_spaces = 4
indentation_style = "Tabs"
newline_style = "Unix"
attr_value_brace_style = "WhenRequired" # "Always", "AlwaysUnlessLit", "WhenRequired" or "Preserve"
macro_names = [ "leptos::view", "view" ] # Macro names which will be formatted
