edition = "2021"
max_width = 120
newline_style = "Unix"
chain_width = 120
fn_call_width = 120
match_block_trailing_comma = true

hard_tabs = true
tab_spaces = 2

# unstable_features = true
# blank_lines_upper_bound = 1
# blank_lines_lower_bound = 1
# format_code_in_doc_comments = true
# imports_layout = "HorizontalVertical"
# control_brace_style = "ClosingNextLine"
# imports_granularity = "Crate"
